# Generated by Django 2.1.7 on 2019-03-04 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 21, 3, 33, 25816), verbose_name='date published'),
        ),
    ]
