# Generated by Django 2.1.7 on 2019-03-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictx', '0002_auto_20190304_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_content',
            new_name='stock_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_published',
        ),
    ]
