# Generated by Django 2.1.7 on 2019-04-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictx', '0004_stock_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
