# Generated by Django 2.1.7 on 2019-04-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictx', '0005_stock_stock_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_link',
        ),
    ]
